### ISSUE TITLE
Have you used the Human 3.6M dataset for your model?

### ISSUE THREAD

**Issue by dulucas** [balakg/posewarp-cvpr2018#1]
Hi Guha,
      Glad that you release your splendid work with us !
      Have your ever test your methods on the Human 3.6M dataset? Because I think this dataset might perfectly fit your method.
      Thanks!

**Comment by dulucas** [comment]
![0_0_2_result](https://user-images.githubusercontent.com/22842511/41506666-bcbfd6ce-7254-11e8-8a9d-24826b76f071.png)
![0_0_13_result](https://user-images.githubusercontent.com/22842511/41506667-c3d45eb2-7254-11e8-8473-ebcbf233869e.png)
![0_0_7_result](https://user-images.githubusercontent.com/22842511/41506668-c9bb439a-7254-11e8-9527-6c6959969646.png)
It works for H3.6M dataset, here are some examples of the network without post-precessing of GAN

**Comment by balakg** [comment]
Thanks, we hadn't tried it yet, though we were going to. These results look good, let us know how it goes!

**Comment by Lotayou** [comment]
@lucasdu007 Nice job. The background seems a bit blurry though, as if the camera was shaking. Is it normal?

**Comment by dulucas** [comment]
@Lotayou It will be better if use the gan provided

**Comment by dulucas** [comment]
@balakg I resize the H3.6M dataset's image to 224x224, and then change the keypoints' number from 14 to 16, and the rest remain unchanged. Every iteration I random choose a pair of images of a same person filmed from a same camera, I only used 1 camera's view, though I think it's better to use all camera's data, because it provides much more training data and at the same time provides 4 images of different views of a same pose, which, in my opinion, will largely boost the performance. These photos are of iteration 44000, it becomes much better after applying gan(iteration 6000).

**Comment by UdonDa** [comment]
@lucasdu007 In H3.6M, which did you use?
Please teach me!
<img width="492" alt="2018-07-06 15 21 51" src="https://user-images.githubusercontent.com/25411643/42362923-75713caa-8130-11e8-98a7-a5d59f8b13d5.png">

**Comment by dulucas** [comment]
actually all of it @UdonDa, you should first extract each scene of each person, and make sure that the input pairs are from same person and same camera(however I suppose that the network will benefit from videos from different viewpoints, which would provide more infos(multi-view) of the same person).

**Comment by UdonDa** [comment]
@lucasdu007 Sounds like being busy. Thank you very much!
