### ISSUE TITLE
Input Pose Data

### ISSUE THREAD

**Issue by erandagan** [balakg/posewarp-cvpr2018#11]
I was wondering how were the video info files with the original poses (`.mat`) generated? Maybe I'm missing something, but the paper only mentions the part about creating the joint heatmaps and not how the joint data was acquired (which I suppose wasn't from a pre-prepared dataset such as MPII, since YouTube videos were used)

Anyway, very impressive work!

**Comment by erandagan** [comment]
And 1 minute later I found the relevant part in the paper :)

**Comment by fanner01** [comment]
how the bbox is calculated?

**Comment by Bowenwu1** [comment]
+1
I wonder how to get the pose keypoints and bbox info of your format in your paper.
