### ISSUE TITLE
License

### ISSUE THREAD

**Issue by DamiAlesh** [balakg/posewarp-cvpr2018#14]
Hello,

Thanks for the amazing work. I have been following this repository very carefully for several months and I am wondering what the license for this code is or shall be. Please let me know if possible. Thank you :)

**Comment by balakg** [comment]
Hi, thanks for the interest. I'l choose a license soon.

**Comment by mareike-vw** [comment]
Hi,
I'm looking to incorporate your work for a school project I'm working on.
Do you have an update for which license this repository will use?

Thanks! :)
