### ISSUE TITLE
Ｑuestion about the test code

### ISSUE THREAD

**Issue by babyjia** [balakg/posewarp-cvpr2018#4]
Hi Guha,
      I am so happy that you've shared it.Now,I have already finished the training process, but I can't find the test code.
     Did you foget to put it on, or do I need to finished by myself?
     Waiting for your reply,thx~

**Comment by balakg** [comment]
I have not uploaded it. There is no real test metric that captures the perceptual quality, but I do have some code that visualizes the various intermediate outputs of the network (e.g. the segmentation masks, fg/bg, etc.). I can add that once I clean it up!

**Comment by hosnasattar** [comment]
Could you please tell when you are going to upload test files? I am wondering how to run your code on some examples?
