### ISSUE TITLE
model missing

### ISSUE THREAD

**Issue by hosnasattar** [balakg/posewarp-cvpr2018#6]
Hi
I would like to use your code, but seems models are missing?! 
Could give a bit intro how to use your code?

**Comment by balakg** [comment]
Yes, I didn't upload the fully trained model here. If that would be useful, I can.

**Comment by thiagoluange** [comment]
I have interest in the full trained model too and how to use your code with the trained model.

**Comment by hosnasattar** [comment]
would be great if you can upload the weights, and models. Thanks

**Comment by hosna** [comment]
could you please also indicate which version of keras and tensorflow you used?
if I try to load vgg19 weights I am getting:
ValueError: You are trying to load a weight file containing 0 layers into a model with 52 layers.

this is due to version mismatch I guess.

**Comment by hosnasattar** [comment]
when I try to use uploaded models I am getting:
 File "posewarp_gan_train.py", line 33, in train
    generator.load_weights('/BS/fashion_dataset/work/posewarp/models/vgg/vgg_100000.h5')
ValueError: Dimension 0 in both shapes must be equal, but are 3 and 64. Shapes are [3,3,64,128] and [64,64,3,3]. for 'Assign_36' (op: 'Assign') with input shapes: [3,3,64,128], [64,64,3,3].
