### ISSUE TITLE
questions for training?

### ISSUE THREAD

**Issue by T-mac93** [balakg/posewarp-cvpr2018#7]
hello, it's a great a work by you. But I want to know about your training set for your network, there are only several examples in your data folder. Thank you too much.

**Comment by balakg** [comment]
We can't release more of them because they are youtube videos without the full sharing license. We just searched for golf, tennis and yoga videos and took ones with reasonably static backgrounds.

**Comment by abhikhanna30** [comment]
Hi @balakg  , just wanted to know how long were the videos just to get an estimate of the amount of data.
Do you think adding more actions would help the model(as in if you tried to) since i wanted to know how i generalizable the model is to other actions.

Thanks,
Abhijeet
